# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-19 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='\u9898\u76ee')),
                ('image', models.ImageField(upload_to='article/%Y/%m', verbose_name='\u5c01\u9762\u56fe')),
                ('content', models.CharField(max_length=10000, verbose_name='\u5185\u5bb9')),
            ],
        ),
    ]
