# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-19 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='click_nums',
            field=models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6570'),
        ),
        migrations.AddField(
            model_name='article',
            name='fav_nums',
            field=models.IntegerField(default=0, verbose_name='\u6536\u85cf\u6570'),
        ),
    ]
