# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-21 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20180419_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article/%Y/%m', verbose_name='\u5c01\u9762\u56fe'),
        ),
    ]
