# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-21 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20180421_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(max_length=10000, verbose_name='\u5185\u5bb9'),
        ),
    ]
